using System;
using System.IO;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Migrations;
using Pomelo.EntityFrameworkCore.MySql.Extensions;

namespace KristaShop.DataAccess.Migrations
{
    /// <summary>
    /// THIS CODE IS NOT GENERATED BY EF CORE
    /// This is a custom migration design to upload 1C tables when creating DB from scratch via migrations
    /// To keep 1C DB structure up to date just replace SQL code in the 20200625063802_Init1cTables.sql file
    /// </summary>
    public partial class Init1cTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.IsMySql()) {
                var assembly = Assembly.GetExecutingAssembly();
                string[] resourceNames = new[] {
                    typeof(Init1cTables).Namespace + ".20200625063802_Init1cTablesStructure.sql",
                };
            
                foreach (var resourceName in resourceNames) {
                    using (Stream stream = assembly.GetManifestResourceStream(resourceName)) {
                        using (StreamReader reader = new StreamReader(stream)) {
                            string sqlResult = reader.ReadToEnd();
                            migrationBuilder.Sql(sqlResult);
                        }
                    }
                }
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            throw new Exception("This migration does not have down method implementation");
        }
    }
}